name: ML Pipeline CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer Python et dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lancer les tests
        run: pytest test_preprocess.py